ZuodaoTech/everyone-can-use-english

.yarnrc.yml
enjoy/package.json
enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/main.ts
enjoy/src/main/db/models/audio.ts
enjoy/src/main/db/models/pronunciation-assessment.ts
enjoy/src/main/db/models/recording.ts
enjoy/src/main/db/models/transcription.ts
enjoy/src/main/db/models/video.ts
enjoy/src/main/ffmpeg.ts
enjoy/src/main/providers/audible-provider.ts
enjoy/src/main/settings.ts
enjoy/src/main/whisper.ts
enjoy/src/main/window.ts
enjoy/src/renderer/components/ffmpeg-check.tsx
enjoy/src/renderer/components/medias/media-player.tsx
enjoy/src/renderer/components/record-button.tsx
enjoy/src/renderer/components/recordings/recording-card.tsx
enjoy/src/renderer/components/recordings/recordings-list.tsx
enjoy/src/renderer/context/app-settings-provider.tsx
enjoy/src/renderer/pages/landing.tsx
yarn.lock

Fix bugs in Apple Mac M1/M2 chip

---

README.md

Updated usage tutorial for Windows system

---

README.md

update readme with how to update enjoy and using latest version

update readme with how to update enjoy and using latest version

---

enjoy/src/renderer/components/videos/ted-talks-segment.tsx

bug：选择community中的vedio，点击Download按钮报错 #147

---

enjoy/src/main/window.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/record-button.tsx
enjoy/src/types/enjoy-app.d.ts

Fix: ask for media access before record

---

enjoy/src/renderer/components/medias/media-caption.tsx
enjoy/src/renderer/components/medias/media-player.tsx

Fix: fix bugs (#218) & (#227)

---

enjoy/src/renderer/components/preferences/preferences.tsx

fix: setting options padding to show option border

---

enjoy/src/main/db/handlers/transcriptions-handler.ts
enjoy/src/main/db/models/transcription.ts
enjoy/src/main/whisper.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/medias/media-transcription.tsx
enjoy/src/renderer/context/ai-settings-provider.tsx
enjoy/src/types/enjoy-app.d.ts

1. may use custom `whisper` exe file
2. display progress when local whipser transcribing

Refactor whisper config

---

enjoy/src/api/client.ts
enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/main/db/handlers/recordings-handler.ts
enjoy/src/main/db/models/audio.ts
enjoy/src/main/db/models/recording.ts
enjoy/src/main/db/models/video.ts
enjoy/src/preload.ts
enjoy/src/renderer/pages/profile.tsx
enjoy/src/types/enjoy-app.d.ts

Fix recording sync

---

enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/main/providers/audible-provider.ts
enjoy/src/renderer/components/audios/audible-books-segment.tsx
enjoy/src/renderer/components/videos/ted-talks-segment.tsx

Display download progress when downloading TED Talk & Audible Book

Feat: display download progress

---

enjoy/src/main/providers/index.ts
enjoy/src/main/providers/youtube-provider.ts
enjoy/src/main/window.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/videos/index.ts
enjoy/src/renderer/components/videos/youtube-videos-segment.tsx
enjoy/src/renderer/pages/home.tsx
enjoy/src/types/enjoy-app.d.ts
enjoy/src/types/index.d.ts

Add YouTube provider to allow users to add YouTube videos from the homepage.
Currently, it is hard-coded to the CNN news channel, we can add more news channel in the future.

Feat: add youtube provider

---

enjoy/src/commands/index.ts
enjoy/src/commands/punctuate.command.ts
enjoy/src/renderer/hooks/use-ai-command.tsx
enjoy/src/renderer/hooks/use-transcribe.tsx

Use AI to correct punctuation issue before alignment

Fix punctuation

---

enjoy/src/renderer/components/medias/media-current-recording.tsx
enjoy/src/renderer/components/medias/media-player-controls.tsx
enjoy/src/renderer/components/preferences/hotkeys.tsx

- Add a hotkey for the compare function, currently hard-coded to `c`. Will try to find a way to let users customize their hotkeys.
- Update "Preferences - Hotkeys" accordingly.
- Fix minor formatting issues.

Fea: add hotkey for compare function

---

enjoy/src/renderer/components/users/users-rankings.tsx

style: delete font style for numbers

---

enjoy/src/renderer/components/preferences/proxy-settings.tsx

Fix proxy config save

---

enjoy/src/main/db/models/audio.ts
enjoy/src/main/db/models/video.ts

Fix extname validation

---

1000-hours/self-training/01-fight.md
1000-hours/self-training/07-encouraging.md
book/chapter2.md
enjoy/lib/youtubedr/README.md
new-edition-drafts/第一轮讲解/12-金钱至上.md

Remove redundant code `<img src="/images/speech-tract-$1.svg" class="themed" />`

Fix mermaid diagrams

---

enjoy/src/main/providers/audible-provider.ts
enjoy/src/main/providers/ted-provider.ts
enjoy/src/main/providers/youtube-provider.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/videos/youtube-videos-segment.tsx
enjoy/src/renderer/pages/home.tsx
enjoy/src/types/enjoy-app.d.ts

- make audible provider work again
- add `@TED` YT channel
- add `@nytimes` YT channel

Fix audible provider & add more YT channel

---

enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/main/db/models/conversation.ts
enjoy/src/renderer/components/conversations/conversation-form.tsx
enjoy/src/renderer/pages/conversations.tsx

Fix: validate conversaton configuation before save

---

enjoy/src/renderer/components/medias/media-caption.tsx
enjoy/src/renderer/components/medias/media-captions/tab-content-translation.tsx
enjoy/src/renderer/context/media-player-provider.tsx
enjoy/src/utils.ts

Fix ipa convert

---

enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/renderer/components/medias/media-current-recording.tsx
enjoy/src/renderer/components/preferences/hotkeys-settings.tsx
enjoy/src/renderer/components/preferences/hotkeys.tsx
enjoy/src/renderer/context/hotkeys-settings-provider.tsx

Improve: refactor hotkey setting & add `A` hotkey

---

enjoy/src/renderer/components/misc/index.ts
enjoy/src/renderer/components/misc/player.tsx
enjoy/src/renderer/components/misc/universal-player.tsx
enjoy/src/renderer/components/misc/wavesurfer-player.tsx
enjoy/src/renderer/components/posts/post-audio.tsx
enjoy/src/renderer/components/posts/post-recording.tsx

Fix multiple players playing

---

enjoy/src/main/whisper.ts
enjoy/src/main/youtubedr.ts
enjoy/src/preload.ts
enjoy/src/renderer/context/media-player-provider.tsx
enjoy/src/renderer/hooks/use-transcriptions.tsx
enjoy/src/types/enjoy-app.d.ts

Fix whisper should abort when cancel

---

enjoy/src/api/client.ts
enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/renderer/components/posts/post-actions.tsx
enjoy/src/renderer/components/posts/post-card.tsx
enjoy/src/renderer/components/posts/posts.tsx
enjoy/src/types/post.d.ts

Feat like posts

---

enjoy/src/renderer/components/medias/media-loading-modal.tsx
enjoy/src/renderer/components/medias/media-transcription-generate-button.tsx
enjoy/src/renderer/components/transcriptions/index.ts
enjoy/src/renderer/components/transcriptions/transcriptions-list.tsx
enjoy/src/types/transcription.d.ts

Feat: download transcription from clound

---

enjoy/src/renderer/components/medias/media-caption.tsx

Fix caption twinkle

---

enjoy/src/main/db/handlers/recordings-handler.ts
enjoy/src/renderer/components/pronunciation-assessments/pronunciation-assessment-form.tsx

Fix recording sequelize unique constraint error

---

enjoy/src/renderer/components/pronunciation-assessments/pronunciation-assessment-form.tsx
enjoy/src/renderer/hooks/use-pronunciation-assessments.tsx

Fix recording update failed

---

enjoy/src/renderer/components/medias/media-player-controls.tsx
enjoy/src/renderer/components/medias/media-transcription.tsx
enjoy/src/renderer/components/recordings/recording-player.tsx

Fix player bug

---

enjoy/src/api/client.ts
enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/main/window.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/misc/login-form.tsx
enjoy/src/renderer/components/preferences/default-engine-settings.tsx
enjoy/src/renderer/components/preferences/index.ts
enjoy/src/renderer/components/preferences/network-state.tsx
enjoy/src/renderer/components/preferences/preferences.tsx
enjoy/src/renderer/components/preferences/proxy-settings.tsx
enjoy/src/types/enjoy-app.d.ts
enjoy/src/types/index.d.ts

feat: 🎸 add net state

---

enjoy/src/main/youtubedr.ts

解决 [#941](https://github.com/ZuodaoTech/everyone-can-use-english/issues/941)，为youtubedr设置enjoy的代理环境变量配置。

Feat:为youtubedr设置enjoy的代理环境变量

---

enjoy/src/i18n/en.json
enjoy/src/i18n/zh-CN.json
enjoy/src/main/db/handlers/audios-handler.ts
enjoy/src/main/db/handlers/videos-handler.ts
enjoy/src/main/db/models/audio.ts
enjoy/src/main/db/models/video.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/audios/audio-card.tsx
enjoy/src/renderer/components/audios/audios-component.tsx
enjoy/src/renderer/components/audios/audios-table.tsx
enjoy/src/renderer/components/medias/media-loading-modal.tsx
enjoy/src/renderer/components/videos/video-card.tsx
enjoy/src/renderer/components/videos/videos-component.tsx
enjoy/src/renderer/components/videos/videos-table.tsx
enjoy/src/types/enjoy-app.d.ts

- remember tab
- alert for resources without source file
- clean up

Improve audio video page

---

enjoy/src/renderer/components/chats/chat-input.tsx

Fix: clear input after sent

---

enjoy/src/main/window.ts

Fix edit in macOS & windows

---

enjoy/src/constants/index.ts
enjoy/src/main/window.ts
enjoy/src/preload.ts
enjoy/src/renderer/components/layouts/sidebar.tsx
enjoy/src/renderer/pages/community.tsx
enjoy/src/types/enjoy-app.d.ts

Embed Community
